// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: proto/LotsService.proto

package lotspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LotsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *LotsRequest) Reset() {
	*x = LotsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LotsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotsRequest) ProtoMessage() {}

func (x *LotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LotsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotsRequest.ProtoReflect.Descriptor instead.
func (*LotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_LotsService_proto_rawDescGZIP(), []int{0}
}

func (x *LotsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count                     int64  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Lots                      int64  `protobuf:"varint,2,opt,name=Lots,proto3" json:"Lots,omitempty"`
	Ticker                    string `protobuf:"bytes,3,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Name                      string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CurrentPrice              string `protobuf:"bytes,5,opt,name=CurrentPrice,proto3" json:"CurrentPrice,omitempty"`
	BuyPrice                  string `protobuf:"bytes,6,opt,name=BuyPrice,proto3" json:"BuyPrice,omitempty"`
	Diff                      string `protobuf:"bytes,7,opt,name=Diff,proto3" json:"Diff,omitempty"`
	DiffPercent               string `protobuf:"bytes,8,opt,name=DiffPercent,proto3" json:"DiffPercent,omitempty"`
	DiffWithCommission        string `protobuf:"bytes,9,opt,name=DiffWithCommission,proto3" json:"DiffWithCommission,omitempty"`
	DiffPercentWithCommission string `protobuf:"bytes,10,opt,name=DiffPercentWithCommission,proto3" json:"DiffPercentWithCommission,omitempty"`
	Currency                  string `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	TotalCost                 string `protobuf:"bytes,12,opt,name=TotalCost,proto3" json:"TotalCost,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LotsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LotsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_LotsService_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stock) GetLots() int64 {
	if x != nil {
		return x.Lots
	}
	return 0
}

func (x *Stock) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetCurrentPrice() string {
	if x != nil {
		return x.CurrentPrice
	}
	return ""
}

func (x *Stock) GetBuyPrice() string {
	if x != nil {
		return x.BuyPrice
	}
	return ""
}

func (x *Stock) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *Stock) GetDiffPercent() string {
	if x != nil {
		return x.DiffPercent
	}
	return ""
}

func (x *Stock) GetDiffWithCommission() string {
	if x != nil {
		return x.DiffWithCommission
	}
	return ""
}

func (x *Stock) GetDiffPercentWithCommission() string {
	if x != nil {
		return x.DiffPercentWithCommission
	}
	return ""
}

func (x *Stock) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Stock) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

type Lot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMoneyRU float64  `protobuf:"fixed64,1,opt,name=TotalMoneyRU,proto3" json:"TotalMoneyRU,omitempty"`
	FreeMoneyRU  float64  `protobuf:"fixed64,2,opt,name=FreeMoneyRU,proto3" json:"FreeMoneyRU,omitempty"`
	Stocks       []*Stock `protobuf:"bytes,3,rep,name=Stocks,proto3" json:"Stocks,omitempty"`
}

func (x *Lot) Reset() {
	*x = Lot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LotsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lot) ProtoMessage() {}

func (x *Lot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LotsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lot.ProtoReflect.Descriptor instead.
func (*Lot) Descriptor() ([]byte, []int) {
	return file_proto_LotsService_proto_rawDescGZIP(), []int{2}
}

func (x *Lot) GetTotalMoneyRU() float64 {
	if x != nil {
		return x.TotalMoneyRU
	}
	return 0
}

func (x *Lot) GetFreeMoneyRU() float64 {
	if x != nil {
		return x.FreeMoneyRU
	}
	return 0
}

func (x *Lot) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type LotsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lot *Lot `protobuf:"bytes,1,opt,name=lot,proto3" json:"lot,omitempty"`
}

func (x *LotsResponse) Reset() {
	*x = LotsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LotsService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotsResponse) ProtoMessage() {}

func (x *LotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LotsService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotsResponse.ProtoReflect.Descriptor instead.
func (*LotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_LotsService_proto_rawDescGZIP(), []int{3}
}

func (x *LotsResponse) GetLot() *Lot {
	if x != nil {
		return x.Lot
	}
	return nil
}

var File_proto_LotsService_proto protoreflect.FileDescriptor

var file_proto_LotsService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4c, 0x6f, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x6f, 0x74, 0x73, 0x22,
	0x23, 0x0a, 0x0b, 0x4c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0xfb, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x4c, 0x6f, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x79, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x75, 0x79, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x69, 0x66, 0x66, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x44, 0x69, 0x66, 0x66, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x66, 0x66,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44,
	0x69, 0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x44, 0x69,
	0x66, 0x66, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x44, 0x69, 0x66, 0x66, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x19, 0x44, 0x69,
	0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x44,
	0x69, 0x66, 0x66, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x73,
	0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x73, 0x74, 0x22, 0x70, 0x0a, 0x03, 0x4c, 0x6f, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x55, 0x12, 0x20, 0x0a,
	0x0b, 0x46, 0x72, 0x65, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x55, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x46, 0x72, 0x65, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x55, 0x12,
	0x23, 0x0a, 0x06, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x22, 0x2b, 0x0a, 0x0c, 0x4c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x74, 0x52, 0x03, 0x6c, 0x6f,
	0x74, 0x32, 0x46, 0x0a, 0x0b, 0x4c, 0x6f, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x37, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x74, 0x73, 0x12, 0x11,
	0x2e, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6c,
	0x6f, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_LotsService_proto_rawDescOnce sync.Once
	file_proto_LotsService_proto_rawDescData = file_proto_LotsService_proto_rawDesc
)

func file_proto_LotsService_proto_rawDescGZIP() []byte {
	file_proto_LotsService_proto_rawDescOnce.Do(func() {
		file_proto_LotsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_LotsService_proto_rawDescData)
	})
	return file_proto_LotsService_proto_rawDescData
}

var file_proto_LotsService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_LotsService_proto_goTypes = []interface{}{
	(*LotsRequest)(nil),  // 0: lots.LotsRequest
	(*Stock)(nil),        // 1: lots.Stock
	(*Lot)(nil),          // 2: lots.Lot
	(*LotsResponse)(nil), // 3: lots.LotsResponse
}
var file_proto_LotsService_proto_depIdxs = []int32{
	1, // 0: lots.Lot.Stocks:type_name -> lots.Stock
	2, // 1: lots.LotsResponse.lot:type_name -> lots.Lot
	0, // 2: lots.LotsService.ActiveLots:input_type -> lots.LotsRequest
	3, // 3: lots.LotsService.ActiveLots:output_type -> lots.LotsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_LotsService_proto_init() }
func file_proto_LotsService_proto_init() {
	if File_proto_LotsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_LotsService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LotsService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LotsService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LotsService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LotsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_LotsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_LotsService_proto_goTypes,
		DependencyIndexes: file_proto_LotsService_proto_depIdxs,
		MessageInfos:      file_proto_LotsService_proto_msgTypes,
	}.Build()
	File_proto_LotsService_proto = out.File
	file_proto_LotsService_proto_rawDesc = nil
	file_proto_LotsService_proto_goTypes = nil
	file_proto_LotsService_proto_depIdxs = nil
}
